version: '3'
services:
  app:
    build: .
    container_name: flask_app
    volumes:
      - ./:/app
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
